services:
  a-board-frontend:
    restart: always
    image: frontend:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXTAUTH_URL=${NEXTAUTH_URL}
        - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
        - NEXT_PUBLIC_SOCKET_URL=${NEXT_PUBLIC_SOCKET_URL}
    environment:
      - NEXTAUTH_URL
      - NEXTAUTH_SECRET
      - NEXT_PUBLIC_API_URL
      - NEXT_PUBLIC_SOCKET_URL
    expose:
      - "3002"
    container_name: a-board-frontend
    networks:
      - network-morroc

  a-board-frontend-nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: a-board-frontend-nginx
    ports:
      - "3002:80"
    depends_on:
      - a-board-frontend
    networks:
      - network-morroc

networks:
  network-morroc:
    external: true