FROM node:20-alpine

#set ENV
ARG NEXTAUTH_URL
ARG NEXTAUTH_SECRET
ARG NEXT_PUBLIC_API_URL
ARG NEXT_PUBLIC_SOCKET_URL

ENV NEXTAUTH_URL=$NEXTAUTH_URL
ENV NEXTAUTH_SECRET=$NEXTAUTH_SECRET
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_SOCKET_URL=$NEXT_PUBLIC_SOCKET_URL

# set working directory

RUN mkdir -p /usr/src/app
 
WORKDIR /usr/src/app

COPY package*.json /usr/src/app

RUN npm install --force

COPY . .

# build app

RUN npm run build

EXPOSE 3002

CMD ["npm", "run", "start"]